- name: Install Remi repository package
  ansible.builtin.dnf:
    name: remi-release
    state: present
  become: true

- name: Enable Redis 6.2 module
  ansible.builtin.command: dnf module enable redis:remi-6.2 -y
  become: true

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present
  become: true

- name: Allow remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  become: true

- name: Start and enable Redis
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes
  become: true