- name: Install python3-dnf for package management
  ansible.builtin.command:
    cmd: dnf install python3-dnf -y
  become: true

- name: Re-gather facts to detect new python libraries
  ansible.builtin.setup:

- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
  become: true

- name: Start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
  become: true

- name: Allow remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  become: true

- name: Restart mongodb to apply changes
  ansible.builtin.service:
    name: mongod
    state: restarted
  become: true