- name: Ensure python3-dnf is installed
  ansible.builtin.dnf:
    name: python3-dnf
    state: present
  become: true
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
  become: true
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

- name: Start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
  become: true

- name: Allow remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  become: true

- name: Restart mongodb to apply changes
  ansible.builtin.service:
    name: mongod
    state: restarted
  become: true